image: docker:19.03.0

cache:
  paths:
    - .yarn

stages:
  - build
  - push-built-image
  - deploy-image
  
variables:
  CONTAINER_IMAGE_MAIN: $DOCKER_REGISTRY_URI/classify-front:${CI_COMMIT_SHORT_SHA}

build-main:
  stage: build
  image: node
  script:
    - yarn install --ignore-optional --frozen-lockfile
    - REACT_APP_API_URI=/api yarn build:prod
  artifacts:
    paths:
      - build
  only:
    - main

build-push-image-main:
  services:
    - docker:19.03.0-dind
  stage: push-built-image
  script:
    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD $DOCKER_REGISTRY_URI
    - docker build -t $CONTAINER_IMAGE_MAIN .
    - docker push $CONTAINER_IMAGE_MAIN
  only:
    - main
  cache: {}

deploy-image-main:
  stage: deploy-image
  image:
    name: bitnami/kubectl:1.14
    entrypoint: [""]
  script:
    - cat $KUBERNETES_CONFIG | base64 -d > ./kubeconfig
    - kubectl set image deployment classify-front-master classify-front-master=$CONTAINER_IMAGE_MAIN --kubeconfig ./kubeconfig --namespace default
  only:
    - main
  cache: {}
